export_plots: false
disable_version_detection: true

module_order:
  - bowtie1:
      name: "Bowtie1 / Seqcluster"
      info: "Alignment summary from Bowtie1 (Seqcluster)."
      path_filters:
        - "alignment_logs/seqcluster/*"
  - bowtie2:
      name: "miRbase Mature mapping (Padded Reference)"
      info: "Alignment summary of reads to miRbase mature padded reference using Bowtie2."
      path_filters:
        - "alignment_logs/mirbase_mature_padded/*"
  - bowtie2:
      name: "Genome alignment"
      info: "Alignment summary of reads to genome using Bowtie2."
      path_filters:
        - "alignment_logs/genome_alignment/*"
      anchor: "bowtie2_genome"
  - mirtop:
      name: "miRNA Quantification (mirtop)"
      info: "Summary statistics from mirtop for miRNA quantification."
      path_filters:
        - "mirtop/mirtop_stats.log"

sp:
  bowtie1:
    fn: "*"
  bowtie2:
    fn: "*"
  mirtop:
    fn: "*mirtop_stats.log"  # Changed to match files with OR without prefix