#-------------------------------------------#
# General Setting 
#-------------------------------------------#

#----- sample meta data file
sample_csv: "sample_fastq_list.csv"
sps: "dre"   # One of "hsa" or "dre" or "mmu"

#----- sequencing config
layout: "single"      # One of "single" or "paired"
use_spikeins: false   # Boolean: true or false
use_umitools: false   # Boolean: true or false
adapter_3prime: "AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC"
#nextseq_trim: "--nextseq-trim=30" # cutadapt flag and value for NextSeq quality trimming; set to "" to disable
nextseq_trim: ""

#-------------------------------------------#
# Spike-in Info
#-------------------------------------------#
sample_with_spikein_finalvolume: 5 # if using NextFLEX, need to change this value
bowtie_spikein_index: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/Labs/howe/250805_smRNA/spike-in_pipeline/GDSC-miRNAseq-analysis-pipeline/refs/spikeins/spikeins_full"
spikein_reference_core: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/Labs/howe/251106_miRNA/refs/spikeins/spikeins_core.fa"

#-------------------------------------------#
# Software Paths for use with "--use-conda" 
#-------------------------------------------#
umitools_path: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/misc/shared-software/tools/umi-tools/umi_tools"
samtools_path: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/misc/sullivan/tools/samtools/samtools-1.11/samtools"
bowtie1_path: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/misc/shared-software/tools/bowtie/bowtie"
bowtie2_path: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/misc/sullivan/tools/bowtie2/bowtie2-2.4.4-linux-x86_64/bowtie2"
seqcluster_path: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/misc/shared-software/tools/seqcluster/bin/seqcluster"
multiqc_path: "multiqc"
python_mirna_venv: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/misc/shared-software/tools/mirna-python-venv/bin/python3"
featurecounts_path: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/misc/sullivan/tools/featurecounts/subread-2.0.1-Linux-x86_64/bin/featureCounts"
fastqc_path: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/misc/sullivan/tools/fastqc/FastQC/fastqc"

#-------------------------------------------#
# Zebrafish Reference File Paths (Bowtie1)
#-------------------------------------------#
bowtie1_mature_index: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/genomic_references/miRNA/miRNA_v2/dre/dre_mature_index/mirbase_mature_drerio"
bowtie1_hairpin_index: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/genomic_references/miRNA/miRNA_v2/dre/dre_hairpin_index/hairpins"
hairpin_gff: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/genomic_references/miRNA/miRNA_v2/dre/dre.gff3"
hairpin_fa: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/genomic_references/miRNA/miRNA_v2/dre/dre_mirbase_hairpins.fa"

#-------------------------------------------#
# Zebrafish Reference File Paths (Bowtie2)
# Note: Bowtie2 index needs to be GRCz11 to match super gtf for annotation
#-------------------------------------------#
padded_mature_index: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/misc/sullivan/tools/snakemake/mirna-seq/DAC-RNAseq-pipeline/refs/mirbase_mature_drerio-padded/mirbase_mature_drerio-padded"
bowtie2_genome_index: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/genomic_references/D_rerio/bowtie2-index/GRCz11"
#annotation_gtf: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/genomic_references/D_rerio/V4.3.2.validated.gtf"
annotation_gtf: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/genomic_references/miRNA/miRNA_v2/dre/DanRer11_smRNAs_super_sorted.gtf"


#-------------------------------------------#
# Utilities
#-------------------------------------------#
#umi_bc_pattern: "'.+(?P<discard_1>AACTGTAGGCACCATCAAT){{s<=2}}(?P<umi_1>.{12})(?P<discard_2>.+)'"
featurecounts_strand: "0" #1 for first read transcription strand, 2 for second.
